### ISSUE TITLE
Root support 

### ISSUE THREAD

**Issue by RoyaleOne** [LinerSRT/SensorsOff#1]
Please add support for magisk too!

**Comment by LinerSRT** [comment]
Magisk as module?

**Comment by RoyaleOne** [comment]
Not as a module, but root privileges instead of shizuku, because now you have to use shizuku ontop of magisk to make this app work and it drains quite a bit of battery

**Comment by LinerSRT** [comment]
Its a bit dificult, cause need use shell commands to operate sensors. For ex. "service call sensorprivacy [method index from aidl] [parameters]"

**Comment by y1111** [comment]
if u have root , u can install sui , which is shizuku as a module in magisk. than u can use it without the shizuku app runing . 
if u already tried , say there if it works https://github.com/LinerSRT/SensorsOff/issues/3
