### ISSUE TITLE
does not install (Invalid apk]

### ISSUE THREAD

**Issue by y1111** [LinerSRT/SensorsOff#2]
i tried in 2 phones . android 10 , a xiaomi 64bit and a moto32bit . 
no releases here install.

(i also tried and in android 14 it installed)

**Comment by JeremiManaluYT** [comment]
same lol

**Comment by abdo1074** [comment]
I can't install it for redmi 8 android 10

**Comment by abdo1074** [comment]
![Screenshot_2024-12-03-17-37-43-922_bin mt plus](https://github.com/user-attachments/assets/d1879735-bc62-47bc-a7c4-8449ec1e889d)
If I want install it that's show this

**Comment by LinerSRT** [comment]
Please read readme. 

> Q: I have device running at Android 10-11 can i use this app?
> A: Supporting older version is not implement for now, but you can try it by yourself. Just lower targetSdk and rebuild it for check out. There is no additional API version check in app
